---
deploy:
  provider: heroku
  api_key: DzIbzsdw+erjSw/rONMWzsG33WsjQe0JT197VVDNjvmHr5dLeoDrKAgmqGs1f+Tz9rqfuSNojo3ojqmpoFvAht738CUZJIaJJ5H9vt/KLlVum0V+ZOqDTGjfEhkW+f3pjuNy1hxvUvJVmyQggFUDPTka/KxQTOxwC3ii7KHG3Q+QswFvAJM4JBoE1d2H/0Ip5oWLfV17UIwsq0SNmt5lDV9EbJc7+LAcDwrH9zhCRAUxyDgqlleo760VEcP2y0R63p0VsBBIo+QX4ywzZl2rIp7l3ZezoQXgoyi+Clpi/t0RtFnjQznwcVSpi7NKmFGH4iOufDRH+S+AeWa35SFjPd6T9dayfsapH91ji73lxQ05PFYZExpE0UsiA8HUhmXdcVQOb6o5TX/bpExc59KISGBTFegn2D+SIFiQXMqMzF8RDDnhxnANVitU9iJNr/1QbkqQSRo5Tf0wjZt7Qed4FxLHRcG8yepc4fRiXBjwe86XYwutqgWchLfSe4TMvLbyf2OHr4hSrD1dqQBx4G/dJkOfEoYkS9u5NAo9reCAO1f4N/RjxoL4K8uC6P60kwDI6FeGRrVT1w5KUwOHbANaG9dzymNVUYK/bANYO0VJywhwHjz8g0tM5F48TooW/eA/VkH3jFxmOxS4DXANINuzcriLUEqdTMQCQTDQebdRxUE=
  app: secure-woodland
  run: "gunicorn app:app"

language: python
python:
  - "3.8"
  
install:
  - pip install -r requirements.txt
  - pip install black
 
script: python tests.py

    
